version: '3.8'
services:
  sponge_vanilla:
    image: kauzas/sponge-vanilla
    container_name: vanilla-1.16.5
    environment:
      - "MINECRAFT_PORT=25565"
      - "MINECRAFT_EULA=true"
      - "MINECRAFT_MAXHEAP=1024M"
      - "SPIGOT_VERSION=1.16.5"
    expose:
      - "25565"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    volumes:
      - ./data:/vanilla:rw